// packages/sdk-ui/src/sisense-context/sisense-context-provider.tsx
import { ClientApplication, createClientApplication } from '../app/client-application';
import { PropsWithChildren, useEffect, useState, type FunctionComponent } from 'react';
import { SisenseContextProviderProps } from '../props';
import { ThemeProvider } from '../theme-provider';
import { ErrorBoundary } from '../error-boundary/error-boundary';
import { SisenseContext } from './sisense-context';
import { I18nProvider } from '../translation/i18n-provider';

/**
 * Sisense Context Provider Component allowing you to connect to
 * a Sisense instance and provide that context
 * to all Compose SDK components in your application.
 *
 * @example
 * Add SisenseContextProvider to the main component of your app as below and then wrap
 * other SDK components inside this component.
 *
 * ```tsx
 * import { Chart, SisenseContextProvider } from '@sisense/sdk-ui';
 * import * as DM from './sample-ecommerce';
 * import { measures } from '@sisense/sdk-data';
 *
 * function App() {
 *   return (
 *     <>
 *       <SisenseContextProvider
 *         url="<instance url>" // replace with the URL of your Sisense instance
 *         token="<api token>" // replace with the API token of your user account
 *       >
 *         <OtherComponent1/>
 *         <OtherComponent2/>
 *       </SisenseContextProvider>
 *     </>
 *   );
 * }
 *
 * export default App;
 * ```
 * @param props - Sisense context provider props
 * @returns A Sisense Context Provider Component
 */
export const SisenseContextProvider: FunctionComponent<
  PropsWithChildren<SisenseContextProviderProps>
> = ({
  defaultDataSource,
  url,
  token,
  wat,
  ssoEnabled,
  children,
  appConfig,
  enableTracking = true,
  showRuntimeErrors = true,
  enableSilentPreAuth = false,
}) => {
  const [app, setApp] = useState<ClientApplication | undefined>();

  const [clientApplicationError, setClientApplicationError] = useState<Error>();

  useEffect(() => {
    let ignore = false;
    void createClientApplication({
      defaultDataSource,
      url,
      token,
      wat,
      ssoEnabled,
      appConfig,
      enableSilentPreAuth,
    })
      .then((newApp) => {
        if (!ignore) {
          setApp(newApp);
        }
      })
      .catch((asyncError: Error) => {
        // set error state to trigger rerender and throw synchronous error
        setClientApplicationError(asyncError);
      });
    return () => {
      ignore = true;
    };
  }, [defaultDataSource, url, token, wat, ssoEnabled, appConfig, enableSilentPreAuth]);

  return (
    <I18nProvider userLanguage={app?.settings.language || app?.settings.serverLanguage}>
      <ErrorBoundary showErrorBox={showRuntimeErrors} error={clientApplicationError}>
        <SisenseContext.Provider value={{ isInitialized: true, app, enableTracking }}>
          <ThemeProvider skipTracking theme={app?.settings.serverThemeSettings}>
            {children}
          </ThemeProvider>
        </SisenseContext.Provider>
      </ErrorBoundary>
    </I18nProvider>
  );
};

// packages/sdk-ui-vue/src/providers/sisense-context-provider/sisense-context-provider.tsx
import { defineComponent, provide, ref } from 'vue';
import type { PropType, Ref } from 'vue';
import type { SisenseContextProviderProps as SisenseContextProviderPropsPreact } from '@sisense/sdk-ui-preact';
import { createClientApplication, type CustomSisenseContext } from '@sisense/sdk-ui-preact';
import { ThemeProvider } from '../theme-provider';
import { defaultSisenseContext, sisenseContextKey } from './sisense-context';

/**
 * Configurations and authentication for Sisense Context.
 *
 * Use one of the following to authenticate:
 *
 * - {@link @sisense/sdk-ui-vue!SisenseContextProviderProps.ssoEnabled | `ssoEnabled`}
 * - {@link @sisense/sdk-ui-vue!SisenseContextProviderProps.token | `token`}
 * - {@link @sisense/sdk-ui-vue!SisenseContextProviderProps.wat | `wat`}
 */
export interface SisenseContextProviderProps extends SisenseContextProviderPropsPreact {}

/**
 * Sisense Context Provider Component allowing you to connect to
 * a Sisense instance and provide that context
 * to all Compose SDK components in your application.
 *
 * @example
 * Here's how to use the `SisenseContextProvider` component to wrap your Sisense-enabled application:
 * Add SisenseContextProvider to the main component of your app as below and then wrap
 * other SDK components inside this component.
 * ```vue
 * <template>
 *   <SisenseContextProvider
 *     :url="sisenseUrl"
 *     :defaultDataSource="defaultDataSource"
 *     :ssoEnabled="true"
 *     :token="authToken"
 *     :wat="watToken"
 *     :appConfig="appConfigurations"
 *   >
 *     <!-- Your application components here -->
 *   </SisenseContextProvider>
 * </template>
 *
 * <script>
 * import { ref } from 'vue';
 * import SisenseContextProvider from './SisenseContextProvider.vue';
 *
 * export default {
 *   components: { SisenseContextProvider },
 *   setup() {
 *     const sisenseUrl = ref('https://your-sisense-instance.com');
 *     const defaultDataSource = ref('default_datasource_id');
 *     const authToken = ref('your_auth_token');
 *     const watToken = ref('your_wat_token');
 *     const appConfigurations = ref({});
 *
 *     return { sisenseUrl, defaultDataSource, authToken, watToken, appConfigurations };
 *   }
 * };
 * </script>
 * ```
 *
 * @param props - Sisense context provider props
 * @returns A Sisense Context Provider Component
 * @group Contexts
 */
export const SisenseContextProvider = defineComponent({
  props: {
    /**
     * {@inheritDoc @sisense/sdk-ui!SisenseContextProviderProps.defaultDataSource}
     *
     * @category Sisense App
     */
    defaultDataSource: String as PropType<SisenseContextProviderProps['defaultDataSource']>,
    /**
     * {@inheritDoc @sisense/sdk-ui!SisenseContextProviderProps.url}
     *
     * @category Sisense App
     */
    url: String as PropType<SisenseContextProviderProps['url']>,
    /**
     * {@inheritDoc @sisense/sdk-ui!SisenseContextProviderProps.ssoEnabled}
     *
     * @category Sisense Authentication
     */
    ssoEnabled: Boolean as PropType<SisenseContextProviderProps['ssoEnabled']>,
    /**
     * {@inheritDoc @sisense/sdk-ui!SisenseContextProviderProps.token}
     *
     * @category Sisense Authentication
     */
    token: String as PropType<SisenseContextProviderProps['token']>,
    /**
     * {@inheritDoc @sisense/sdk-ui!SisenseContextProviderProps.wat}
     *
     * @category Sisense Authentication
     */
    wat: String as PropType<SisenseContextProviderProps['wat']>,
    /**
     * {@inheritDoc @sisense/sdk-ui!SisenseContextProviderProps.appConfig}
     *
     * @category Sisense App
     */
    appConfig: Object as PropType<SisenseContextProviderProps['appConfig']>,
    /**
     * @internal
     */
    showRuntimeErrors: {
      type: Boolean as PropType<SisenseContextProviderProps['showRuntimeErrors']>,
      default: defaultSisenseContext.errorBoundary.showErrorBox,
    },
  },

  setup(props, { slots }) {
    const context = ref<CustomSisenseContext>({
      ...defaultSisenseContext,
      isInitialized: true,
      errorBoundary: {
        showErrorBox: props.showRuntimeErrors ?? true,
      },
      tracking: {
        ...defaultSisenseContext.tracking,
        enabled: props.appConfig?.trackingConfig?.enabled ?? true,
      },
    });
    createClientApplication(props as SisenseContextProviderProps).then((newApp) => {
      context.value = {
        ...context.value,
        app: newApp,
      };
    });

    provide(sisenseContextKey, context as Ref<CustomSisenseContext>);

    return () => {
      return (
        <ThemeProvider theme={context.value.app?.settings.serverThemeSettings}>
          {slots.default?.()}
        </ThemeProvider>
      );
    };
  },
});
