// packages/sdk-ui-angular/src/lib/components/dashboard/dashboard.component.ts
import {
  AfterViewInit,
  Component,
  ElementRef,
  Input,
  OnChanges,
  OnDestroy,
  ViewChild,
} from '@angular/core';
import {
  ComponentAdapter,
  Dashboard as DashboardPreact,
  type DashboardProps as DashboardPropsPreact,
} from '@sisense/sdk-ui-preact';

import {
  createPluginsContextConnector,
  createSisenseContextConnector,
  createThemeContextConnector,
  rootId,
  styles,
  template,
} from '../../component-wrapper-helpers';
import { translateToPreactDashboardProps } from '../../helpers/dashboard-props-preact-translator';
import { PluginsService } from '../../services/plugins.service';
import { SisenseContextService } from '../../services/sisense-context.service';
import { ThemeService } from '../../services/theme.service';
import type { DashboardConfig } from '../../types';
import { WidgetProps } from '../widgets/widget.component';

/**
 * Props of the {@link DashboardComponent}.
 */
export interface DashboardProps extends Omit<DashboardPropsPreact, 'widgets'> {
  /**
   * {@inheritDoc @sisense/sdk-ui!DashboardProps.config}
   */
  config?: DashboardConfig;
  /**
   * {@inheritDoc @sisense/sdk-ui!DashboardProps.widgets}
   */
  widgets: WidgetProps[];
}

/**
 * An Angular component used for easily rendering a dashboard created in Sisense Fusion.
 *
 * **Note:** Dashboard and Widget extensions based on JS scripts and add-ons in Fusion – for example, Blox and Jump To Dashboard – are not supported.
 *
 * @example
 * ```html
 * <csdk-dashboard
 *  *ngIf="dashboard"
 *  [title]="dashboard.title"
 *  [layoutOptions]="dashboard.layoutOptions"
 *  [widgets]="dashboard.widgets"
 *  [filters]="dashboard.filters"
 *  [defaultDataSource]="dashboard.defaultDataSource"
 *  [widgetsOptions]="dashboard.widgetsOptions"
 * />
 * ```
 *
 * ```ts
 * import { Component } from '@angular/core';
 * import {
 *   type DashboardProps,
 *   DashboardService,
 *   dashboardModelTranslator,
 * } from '@sisense/sdk-ui-angular';
 *
 * @Component({
 *  selector: 'app-dashboard',
 *  templateUrl: './dashboard.component.html',
 *  styleUrls: ['./dashboard.component.scss'],
 * })
 * export class DashboardComponent {
 *
 *  dashboard: DashboardProps | null = null;
 *
 *  constructor(private dashboardService: DashboardService) {}
 *
 *  async ngOnInit(): Promise<void> {
 *    const dashboardModel = await this.dashboardService.getDashboardModel('your-dashboard-oid', { includeWidgets: true, includeFilters: true });
 *    this.dashboard = dashboardModelTranslator.toDashboardProps(dashboardModel);
 *  }
 * ```
 *
 * To learn more about this and related dashboard components,
 * see [Embedded Dashboards](/guides/sdk/guides/dashboards/index.html).
 * @group Dashboards
 */
@Component({
  selector: 'csdk-dashboard',
  template,
  styles,
})
export class DashboardComponent implements AfterViewInit, OnChanges, OnDestroy {
  /**
   * @internal
   */
  @ViewChild(rootId)
  preactRef!: ElementRef<HTMLDivElement>;

  /**
   * {@inheritDoc @sisense/sdk-ui!DashboardProps.title}
   */
  @Input()
  title: DashboardProps['title'];

  /**
   * {@inheritDoc @sisense/sdk-ui!DashboardProps.layoutOptions}
   */
  @Input()
  layoutOptions: DashboardProps['layoutOptions'];

  /**
   * {@inheritDoc @sisense/sdk-ui!DashboardProps.config}
   */
  @Input()
  config: DashboardProps['config'];

  /**
   * {@inheritDoc @sisense/sdk-ui!DashboardProps.widgets}
   */
  @Input()
  widgets!: DashboardProps['widgets'];

  /**
   * {@inheritDoc @sisense/sdk-ui!DashboardProps.filters}
   */
  @Input()
  filters: DashboardProps['filters'];

  /**
   * {@inheritDoc @sisense/sdk-ui!DashboardProps.defaultDataSource}
   */
  @Input()
  defaultDataSource: DashboardProps['defaultDataSource'];

  /**
   * {@inheritDoc @sisense/sdk-ui!DashboardProps.widgetsOptions}
   */
  @Input()
  widgetsOptions: DashboardProps['widgetsOptions'];

  /**
   * {@inheritDoc @sisense/sdk-ui!DashboardProps.styleOptions}
   */
  @Input()
  styleOptions: DashboardProps['styleOptions'];

  /**
   * {@inheritDoc @sisense/sdk-ui!DashboardProps.tabbersOptions}
   *
   * @internal
   */
  @Input()
  tabbersOptions: DashboardProps['tabbersOptions'];

  private componentAdapter: ComponentAdapter<typeof DashboardPreact>;

  /**
   * Constructor for the `Dashboard` component.
   *
   * @param sisenseContextService - Sisense context service
   * @param themeService - Theme service
   */
  constructor(
    /**
     * Sisense context service
     *
     * @category Constructor
     */
    public sisenseContextService: SisenseContextService,
    /**
     * Theme service
     *
     * @category Constructor
     */
    public themeService: ThemeService,
    /**
     * Plugin service
     *
     * @internal
     * @category Constructor
     */
    public pluginService: PluginsService,
  ) {
    this.componentAdapter = new ComponentAdapter(DashboardPreact, [
      createSisenseContextConnector(this.sisenseContextService),
      createThemeContextConnector(this.themeService),
      createPluginsContextConnector(this.pluginService),
    ]);
  }

  /**
   * @internal
   */
  ngAfterViewInit() {
    this.componentAdapter.render(this.preactRef.nativeElement, this.getPreactComponentProps());
  }

  /**
   * @internal
   */
  ngOnChanges() {
    if (this.preactRef) {
      this.componentAdapter.render(this.preactRef.nativeElement, this.getPreactComponentProps());
    }
  }

  private getPreactComponentProps(): DashboardPropsPreact {
    return translateToPreactDashboardProps({
      title: this.title,
      layoutOptions: this.layoutOptions,
      config: this.config,
      widgets: this.widgets,
      filters: this.filters,
      defaultDataSource: this.defaultDataSource,
      widgetsOptions: this.widgetsOptions,
      styleOptions: this.styleOptions,
      tabbersOptions: this.tabbersOptions,
    });
  }

  /**
   * @internal
   */
  ngOnDestroy() {
    this.componentAdapter.destroy();
  }
}

// packages/sdk-ui/src/dashboard/dashboard.tsx
import { DashboardProps } from '@/dashboard/types';
import { DashboardContainer } from '@/dashboard/components/dashboard-container';
import { ThemeProvider } from '@/theme-provider';
import { asSisenseComponent } from '@/decorators/component-decorators/as-sisense-component';
import { useDashboardThemeInternal } from './use-dashboard-theme';
import { useComposedDashboardInternal } from './use-composed-dashboard';
import { Filter, FilterRelations } from '@sisense/sdk-data';
import { useCallback, useEffect } from 'react';
import { usePlugins } from '@/plugins-provider';
import { TabberWidget } from '@/widgets/tabber-widget';
import { useSisenseContext } from '@/sisense-context/sisense-context';

export enum DashboardChangeType {
  /** Dashboard filters have been updated */
  FILTERS_UPDATE = 'FILTERS.UPDATE',
  /** Filters panel collapsed state changed */
  UI_FILTERS_PANEL_COLLAPSE = 'UI.FILTERS.PANEL.COLLAPSE',
}

export type DashboardChangeAction =
  | {
      type: DashboardChangeType.FILTERS_UPDATE;
      payload: Filter[] | FilterRelations;
    }
  | {
      type: DashboardChangeType.UI_FILTERS_PANEL_COLLAPSE;
      payload: boolean;
    };

/**
 * React component that renders a dashboard whose elements are customizable. It includes internal logic of applying common filters to widgets.
 *
 * **Note:** Dashboard and Widget extensions based on JS scripts and add-ons in Fusion – for example, Blox and Jump To Dashboard – are not supported.
 *
 * @example
 *
 * Example of rendering a Fusion dashboard using the `useGetDashboardModel hook and the `Dashboard` component.
 *
 * ```ts
 * import { Dashboard, useGetDashboardModel, dashboardModelTranslator } from '@sisense/sdk-ui';

const CodeExample = () => {
  const { dashboard } = useGetDashboardModel({
    dashboardOid: '65a82171719e7f004018691c',
    includeFilters: true,
    includeWidgets: true,
  });

  return (
    <>
      {dashboard && (
        <Dashboard {...dashboardModelTranslator.toDashboardProps(dashboard)} />
      )}
    </>
  );
};

export default CodeExample;
 * ```
 *
 * To learn more about this and related dashboard components,
 * see [Embedded Dashboards](/guides/sdk/guides/dashboards/index.html).
 * @group Dashboards
 */
export const Dashboard = asSisenseComponent({
  componentName: 'Dashboard',
})(
  ({
    title = '',
    layoutOptions,
    config,
    widgets,
    filters,
    defaultDataSource,
    widgetsOptions,
    tabbersOptions,
    styleOptions,
    onChange,
    enableFilterEditor = false,
  }: DashboardProps) => {
    const { themeSettings } = useDashboardThemeInternal({ styleOptions });
    const { registerPlugin } = usePlugins();
    const app = useSisenseContext().app;

    useEffect(() => {
      const tabberEnabled = app?.settings?.tabberConfig?.enabled || false;
      if (tabberEnabled) {
        registerPlugin('WidgetsTabber', TabberWidget);
      }
    }, [app?.settings?.tabberConfig?.enabled, registerPlugin]);
    const {
      dashboard: { filters: dashboardFilters = [], widgets: dashboardWidgets },
      setFilters,
      layoutOptions: updatedLayoutOptions,
    } = useComposedDashboardInternal(
      {
        filters,
        widgets,
        widgetsOptions,
        layoutOptions,
        tabbersOptions,
      },
      {
        onFiltersChange: useCallback(
          (filters: Filter[] | FilterRelations) => {
            onChange?.({ type: DashboardChangeType.FILTERS_UPDATE, payload: filters });
          },
          [onChange],
        ),
      },
    );

    return (
      <ThemeProvider theme={themeSettings}>
        <DashboardContainer
          title={title}
          layoutOptions={updatedLayoutOptions}
          config={config}
          widgets={dashboardWidgets}
          defaultDataSource={defaultDataSource}
          filters={dashboardFilters}
          onFiltersChange={setFilters}
          onChange={onChange}
          enableFilterEditor={enableFilterEditor}
        />
      </ThemeProvider>
    );
  },
);
