// packages/sdk-ui/src/domains/visualizations/components/pivot-table/pivot-table.tsx
/* eslint-disable promise/catch-or-return */
import { useCallback, useEffect, useMemo, useState } from 'react';

import {
  EVENT_SORTING_SETTINGS_CHANGED,
  type SortingSettingsChangePayload,
} from '@sisense/sdk-pivot-ui';

import { useSisenseContext } from '@/infra/contexts/sisense-context/sisense-context';
import { useThemeContext } from '@/infra/contexts/theme-provider';
import { asSisenseComponent } from '@/infra/decorators/component-decorators/as-sisense-component';
import { TranslatableError } from '@/infra/translation/translatable-error';
import { PivotTableProps } from '@/props';
import {
  DEFAULT_PIVOT_TABLE_SIZE,
  DynamicSizeContainer,
} from '@/shared/components/dynamic-size-container';
import { type ContainerSize } from '@/shared/components/dynamic-size-container/dynamic-size-container';
import { LoadingOverlay } from '@/shared/components/loading-overlay';
import { NoResultsOverlay } from '@/shared/components/no-results-overlay/no-results-overlay';
import { useHasChanged } from '@/shared/hooks/use-has-changed';
import { useSyncedState } from '@/shared/hooks/use-synced-state';

import { useApplyPivotTableFormatting } from './hooks/use-apply-pivot-table-formatting';
import { usePivotTableQuery } from './hooks/use-get-pivot-table-query';
import { usePivotBuilder } from './hooks/use-pivot-builder';
import { usePivotClient } from './hooks/use-pivot-client';
import { usePivotDataLoading } from './hooks/use-pivot-data-loading';
import { usePivotDataService } from './hooks/use-pivot-data-service';
import { usePivotTableDataOptionsInternal } from './hooks/use-pivot-table-data-options-internal';
import { useRenderPivot } from './hooks/use-render-pivot';
import { preparePivotRowsSortCriteriaList } from './sorting-utils';

export const PIVOT_WIDGET_PADDING = 8;
const NO_RESULTS_HEIGHT = 200;

/**
 * Pivot table with pagination.
 *
 * @example
 * (1) Example of PivotTable from the `Sample ECommerce` data model:
 *
 * ```tsx
 * <PivotTable
 *   dataSet={DM.DataSource}
 *   dataOptions={{
 *     rows: [
 *       { column: DM.Category.Category, includeSubTotals: true },
 *       { column: DM.Commerce.AgeRange, includeSubTotals: true },
 *       DM.Commerce.Condition,
 *     ],
 *     columns: [{ column: DM.Commerce.Gender, includeSubTotals: true }],
 *     values: [
 *       {
 *         column: measureFactory.sum(DM.Commerce.Cost, 'Total Cost'),
 *         dataBars: true,
 *         totalsCalculation: 'sum',
 *       },
 *       {
 *         column: measureFactory.sum(DM.Commerce.Revenue, 'Total Revenue'),
 *         totalsCalculation: 'sum',
 *       },
 *     ],
 *     grandTotals: { rows: true, columns: true },
 *   }}
 *   filters={[filterFactory.members(DM.Commerce.Gender, ['Female', 'Male'])]}
 *   styleOptions={{ width: 1000, height: 600, rowsPerPage: 50 }}
 * />
 * ```
 * <img src="media://pivot-example-1.png" width="800px" />
 *
 * (2) Example of PivotTable with the predefined sorting configuration:
 * - Sort "Condition" row by its values in Ascending order. This is equivalent to users clicking on the "Condition" row heading and hit Sort Ascending (A-Z)
 * - Sort "Category" row by "Total Cost" values under the "columns" values of "Female" (for Gender) and "0-18" (for AgeRange) in Descending order.
 * This is equivalent to users clicking on the "Total Cost" value heading under "Female" (for Gender) and "0-18" (for AgeRange) and sort "Category (Subtotals)" in Descending (9-1)
 *
 * ```tsx
 * <PivotTable
 *   dataSet={DM.DataSource}
 *   dataOptions={{
 *     rows: [
 *       {
 *         column: DM.Category.Category,
 *         includeSubTotals: true,
 *         sortType: {
 *           direction: 'sortDesc',
 *           by: {
 *             valuesIndex: 0,
 *             columnsMembersPath: ['Female', '0-18']
 *           }
 *         }
 *       },
 *       {
 *         column: DM.Commerce.Condition,
 *         sortType: {
 *           direction: 'sortAsc'
 *         }
 *       },
 *     ],
 *     columns: [
 *       DM.Commerce.Gender,
 *       DM.Commerce.AgeRange
 *     ],
 *     values: [
 *       measureFactory.sum(DM.Commerce.Cost, 'Total Cost'),
 *       measureFactory.sum(DM.Commerce.Quantity, 'Total Quantity'),
 *     ],
 *   }}
 * />
 * ```
 *
 * <img src="media://pivot-sorting-example-1.png" width="800px" />
 *
 * (3) Example of PivotTable with auto content width enabled:
 * When {@link PivotTableStyleOptions.isAutoContentWidth | `isAutoContentWidth: true`} is set, all vertical columns will be resized to fit within the component width without requiring horizontal scroll.
 *
 * ```tsx
 * <PivotTable
 *   dataSet={DM.DataSource}
 *   dataOptions={{
 *     rows: [DM.Category.Category],
 *     columns: [DM.Commerce.Gender],
 *     values: [
 *       measureFactory.sum(DM.Commerce.Cost, 'Total Cost'),
 *       measureFactory.sum(DM.Commerce.Revenue, 'Total Revenue'),
 *     ],
 *   }}
 *   styleOptions={{
 *     width: 800,
 *     height: 600,
 *     isAutoContentWidth: true,
 *     rowsPerPage: 50,
 *   }}
 * />
 * ```
 * <img src="media://pivot-auto-content-width-true.png" width="800px" />
 *
 * @remarks
 * Configuration options can also be applied within the scope of a `<SisenseContextProvider>` to control the default behavior of PivotTable, by changing available settings within `appConfig.chartConfig.tabular.*`
 *
 * Follow the link to {@link AppConfig} for more details on the available settings.
 *
 * @param props - Pivot Table properties
 * @returns Pivot Table component
 * @group Data Grids
 */
export const PivotTable = asSisenseComponent({
  componentName: 'PivotTable',
})((pivotTableProps: PivotTableProps) => {
  const {
    dataSet,
    dataOptions,
    filters,
    highlights,
    refreshCounter = 0,
    onHeightChange,
    onDataPointClick,
    onDataPointContextMenu,
  } = pivotTableProps;
  const styleOptions = useMemo(
    () => pivotTableProps.styleOptions ?? {},
    [pivotTableProps.styleOptions],
  );
  const [size, setSize] = useState<ContainerSize | null>(null);
  const [pivotTotalHeight, setPivotTotalHeight] = useState<number | null>(null);
  // retrieve and validate the pivot client
  const { app } = useSisenseContext();
  const { themeSettings } = useThemeContext();
  const pivotQueryClient = app?.pivotQueryClient;

  if (!pivotQueryClient) {
    throw new TranslatableError('errors.noPivotClient');
  }

  const { dataOptionsInternal, updateSort } = usePivotTableDataOptionsInternal({ dataOptions });

  // get the jaql from the pivot table props
  const { error, jaql } = usePivotTableQuery({
    dataSet,
    dataOptionsInternal,
    filters,
    highlights,
  });
  if (error) {
    throw error;
  }

  const pivotClient = usePivotClient({ pivotQueryClient });
  const pivotBuilder = usePivotBuilder({ pivotClient });
  const isJaqlChanged = useHasChanged(jaql);
  const isForceReload = refreshCounter > 0 && useHasChanged(refreshCounter);

  const [pageSize, setPageSize] = useSyncedState(
    typeof styleOptions?.rowsPerPage === 'number' && !isNaN(styleOptions?.rowsPerPage)
      ? styleOptions?.rowsPerPage
      : pivotBuilder.defaultPageSize,
  );

  if (pageSize !== pivotBuilder.pageSize) {
    pivotBuilder.updatePageSize(pageSize);
  }

  const dataService = usePivotDataService({
    pivotClient,
    pivotBuilder,
    shouldBeRecreated: isJaqlChanged || isForceReload,
  });
  useApplyPivotTableFormatting({
    dataService,
    dataOptions: dataOptionsInternal,
    onDataCellFormat: pivotTableProps.onDataCellFormat,
    onHeaderCellFormat: pivotTableProps.onHeaderCellFormat,
  });

  const handlePivotHeightChange = useCallback(
    (height: number) => {
      onHeightChange?.(height);
      setPivotTotalHeight(height);
    },
    [onHeightChange],
  );

  const { pivotElement } = useRenderPivot({
    pivotBuilder,
    dataOptions: dataOptionsInternal,
    styleOptions,
    themeSettings,
    size,
    allowHtml: app?.settings?.chartConfig?.tabular?.htmlContent?.enabled,
    sanitizeHtml: app?.settings?.chartConfig?.tabular?.htmlContent?.sanitizeContents,
    isFullWidth: styleOptions.isAutoContentWidth,
    onTotalHeightChange: handlePivotHeightChange,
    onDataPointClick,
    onDataPointContextMenu,
    pageSize: pageSize,
    imageColumns: styleOptions.imageColumns,
    onPageSizeChange: setPageSize,
    alwaysShowResultsPerPage:
      styleOptions.alwaysShowResultsPerPage ??
      app?.settings?.chartConfig?.tabular?.alwaysShowResultsPerPage ??
      false,
  });

  // The pivot data layer depends on the pivot's render props.
  // Therefore, "usePivotDataLoading" hook should be invoked only after the "useRenderPivot" hook.
  const { isLoading, isNoResults } = usePivotDataLoading({
    jaql,
    pivotBuilder,
    isForceReload,
  });

  const onSort = useCallback(
    (payload: SortingSettingsChangePayload) => {
      const rowsSortCriteriaList = preparePivotRowsSortCriteriaList(payload, dataOptionsInternal);
      updateSort({
        rows: rowsSortCriteriaList,
      });
    },
    [dataOptionsInternal, updateSort],
  );

  useEffect(() => {
    pivotBuilder.on(EVENT_SORTING_SETTINGS_CHANGED, onSort);
    return () => {
      pivotBuilder.off(EVENT_SORTING_SETTINGS_CHANGED, onSort);
    };
  }, [pivotBuilder, onSort]);

  const updateSize = useCallback(
    (containerSize: ContainerSize) => {
      const height = containerSize.height - PIVOT_WIDGET_PADDING;
      const width = containerSize.width - 2 * PIVOT_WIDGET_PADDING;
      if (width !== size?.width || height !== size?.height) {
        setSize({ width, height });
      }
    },
    [size, setSize],
  );

  useEffect(() => {
    if (styleOptions?.isAutoHeight && isNoResults) {
      onHeightChange?.(NO_RESULTS_HEIGHT);
    }
  }, [pivotTotalHeight, styleOptions?.isAutoHeight, isNoResults, onHeightChange]);

  return (
    <DynamicSizeContainer
      defaultSize={DEFAULT_PIVOT_TABLE_SIZE}
      size={{
        width: styleOptions?.width,
        height:
          styleOptions?.isAutoHeight && !isNoResults
            ? pivotTotalHeight ?? styleOptions?.height
            : styleOptions?.height,
      }}
      onSizeChange={updateSize}
    >
      <LoadingOverlay isVisible={isLoading}>
        <>
          {isNoResults && <NoResultsOverlay iconType="table" />}
          <div
            aria-label="pivot-table-root"
            style={{
              padding: `${PIVOT_WIDGET_PADDING}px ${PIVOT_WIDGET_PADDING}px 0 ${PIVOT_WIDGET_PADDING}px`,
            }}
          >
            {pivotElement}
          </div>
        </>
      </LoadingOverlay>
    </DynamicSizeContainer>
  );
});

// packages/sdk-ui-angular/src/lib/components/charts/pivot-table.component.ts
import {
  AfterViewInit,
  Component,
  ElementRef,
  Input,
  OnChanges,
  OnDestroy,
  ViewChild,
} from '@angular/core';
import {
  ComponentAdapter,
  PivotTable as PivotTablePreact,
  type PivotTableProps as PivotTablePropsPreact,
} from '@sisense/sdk-ui-preact';

import {
  createSisenseContextConnector,
  createThemeContextConnector,
  rootId,
  styles,
  template,
} from '../../component-wrapper-helpers';
import { SisenseContextService } from '../../services';
import { ThemeService } from '../../services';

/**
 * Props of the {@link PivotTableComponent}.
 */
export interface PivotTableProps extends PivotTablePropsPreact {}

/**
 * Pivot Table with and pagination.
 *
 * @example
 * ```html
 *  <csdk-pivot-table
 *    [dataSet]="pivotTable.dataSet"
 *    [dataOptions]="pivotTable.dataOptions"
 *    [filters]="pivotTable.filters"
 *    [styleOptions]="pivotTable.styleOptions"
 *  />
 * ```
 * ```ts
import { Component } from '@angular/core';
import { measureFactory, filterFactory } from '@sisense/sdk-data';
import * as DM from '../../assets/sample-ecommerce';
import type { PivotTableDataOptions } from '@sisense/sdk-ui-angular';

@Component({
  selector: 'app-analytics',
  templateUrl: './analytics.component.html',
  styleUrls: ['./analytics.component.scss'],
})
export class AnalyticsComponent {

  pivotTableDataOptions: PivotTableDataOptions = {
    rows: [
      { column: DM.Category.Category, includeSubTotals: true },
      { column: DM.Commerce.AgeRange, includeSubTotals: true },
      DM.Commerce.Condition,
    ],
    columns: [{ column: DM.Commerce.Gender, includeSubTotals: true }],
    values: [
      measureFactory.sum(DM.Commerce.Cost, 'Total Cost'),
      {
        column: measureFactory.sum(DM.Commerce.Revenue, 'Total Revenue'),
        totalsCalculation: 'sum',
        dataBars: true,
      },
    ],
    grandTotals: { rows: true, columns: true },
  };

  pivotTable = {
    dataSet: DM.DataSource,
    dataOptions: this.pivotTableDataOptions,
    filters: [filterFactory.members(DM.Commerce.Gender, ['Female', 'Male'])],
    styleOptions: { width: 1400, height: 600, rowsPerPage: 50 },
  };

}
 * ```
 * <img src="media://angular-pivot-table-example.png" width="800px" />
 *
 * @remarks
 * Configuration options can also be applied within the scope of a `<SisenseContextProvider>` to control the default behavior of PivotTable, by changing available settings within `appConfig.chartConfig.tabular.*`
 *
 * Follow the link to {@link AppConfig} for more details on the available settings.
 *
 * @group Data Grids
 */
@Component({
  selector: 'csdk-pivot-table',
  template,
  styles,
})
export class PivotTableComponent implements AfterViewInit, OnChanges, OnDestroy {
  /** @internal */
  @ViewChild(rootId)
  preactRef!: ElementRef<HTMLDivElement>;

  /**
   * {@inheritDoc @sisense/sdk-ui!PivotTableProps.dataSet}
   *
   * @category Data
   */
  @Input()
  dataSet: PivotTableProps['dataSet'];

  /**
   * {@inheritDoc @sisense/sdk-ui!PivotTableProps.dataOptions}
   *
   * @category Data
   */
  @Input()
  dataOptions!: PivotTableProps['dataOptions'];

  /**
   * {@inheritDoc @sisense/sdk-ui!PivotTableProps.filters}
   *
   * @category Data
   */
  @Input()
  filters: PivotTableProps['filters'];

  /**
   * {@inheritDoc @sisense/sdk-ui!PivotTableProps.highlights}
   *
   * @category Data
   */
  @Input()
  highlights: PivotTableProps['highlights'];

  /**
   * {@inheritDoc @sisense/sdk-ui!PivotTableProps.styleOptions}
   *
   * @category Representation
   */
  @Input()
  styleOptions: PivotTableProps['styleOptions'];

  private componentAdapter: ComponentAdapter<typeof PivotTablePreact>;

  constructor(
    private sisenseContextService: SisenseContextService,
    private themeService: ThemeService,
  ) {
    this.componentAdapter = new ComponentAdapter(PivotTablePreact, [
      createSisenseContextConnector(this.sisenseContextService),
      createThemeContextConnector(this.themeService),
    ]);
  }

  /** @internal */
  ngAfterViewInit() {
    this.componentAdapter.render(this.preactRef.nativeElement, this.getPreactComponentProps());
  }

  /** @internal */
  ngOnChanges() {
    if (this.preactRef) {
      this.componentAdapter.render(this.preactRef.nativeElement, this.getPreactComponentProps());
    }
  }

  private getPreactComponentProps(): PivotTablePropsPreact {
    return {
      dataSet: this.dataSet,
      dataOptions: this.dataOptions,
      filters: this.filters,
      highlights: this.highlights,
      styleOptions: this.styleOptions,
    };
  }

  /** @internal */
  ngOnDestroy() {
    this.componentAdapter.destroy();
  }
}
