// packages/sdk-ui-angular/src/lib/components/charts/area-chart.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { type AreaChartProps as AreaChartPropsPreact } from '@sisense/sdk-ui-preact';

import { type ChartType } from '../../sdk-ui-core-exports';
import {
  RegularChartEventProps,
  WithoutPreactChartEventProps,
} from '../../types/chart-event-props';
import { DataPointEvent, DataPointsEvent } from '../../types/data-point';

/**
 * Props of the {@link AreaChartComponent} component.
 */
export interface AreaChartProps
  extends WithoutPreactChartEventProps<AreaChartPropsPreact>,
    RegularChartEventProps {}

/**
 * A component similar to a {@link LineChartComponent},
 * but with filled in areas under each line and an option to display them as stacked.
 *
 * @example
 * ```ts
 * import { Component } from '@angular/core';
 * import { measureFactory } from '@sisense/sdk-data';
 * import * as DM from './sample-ecommerce';
 *
 * @Component({
 *   selector: 'code-example',
 *   template: `
 *     <csdk-area-chart [dataSet]="DM.DataSource" [dataOptions]="dataOptions"></csdk-area-chart>
 *   `,
 * })
 * export class CodeExample {
 *   DM = DM;
 *   dataOptions = {
 *     category: [DM.Commerce.Date.Quarters],
 *     value: [measureFactory.sum(DM.Commerce.Revenue, 'Total Revenue')],
 *     breakBy: [],
 *   };
 * }
 * ```
 * <img src="media://area-chart-example-1.png" width="700px" />
 * @group Charts
 */
@Component({
  standalone: false,
  selector: 'csdk-area-chart',
  template: `
    <csdk-chart
      [chartType]="chartType"
      [dataSet]="dataSet"
      [dataOptions]="dataOptions"
      [filters]="filters"
      [highlights]="highlights"
      [styleOptions]="styleOptions"
      [beforeRender]="beforeRender"
      [dataReady]="dataReady"
      (dataPointClick)="dataPointClick.emit($any($event))"
      (dataPointContextMenu)="dataPointContextMenu.emit($any($event))"
      (dataPointsSelect)="dataPointsSelect.emit($any($event))"
    />
  `,
})
export class AreaChartComponent {
  /**
   * {@inheritDoc @sisense/sdk-ui!AreaChartProps.dataSet}
   *
   * @category Data
   */
  @Input()
  dataSet: AreaChartProps['dataSet'];

  /**
   * {@inheritDoc @sisense/sdk-ui!AreaChartProps.dataOptions}
   *
   * @category Chart
   */
  @Input()
  dataOptions!: AreaChartProps['dataOptions'];

  /**
   * {@inheritDoc @sisense/sdk-ui!AreaChartProps.filters}
   *
   * @category Data
   */
  @Input()
  filters: AreaChartProps['filters'];

  /**
   * {@inheritDoc @sisense/sdk-ui!AreaChartProps.highlights}
   *
   * @category Data
   */
  @Input()
  highlights: AreaChartProps['highlights'];

  /**
   * {@inheritDoc @sisense/sdk-ui!AreaChartProps.styleOptions}
   *
   * @category Chart
   */
  @Input()
  styleOptions: AreaChartProps['styleOptions'];

  /**
   * {@inheritDoc @sisense/sdk-ui!AreaChartProps.onBeforeRender}
   *
   * @category Callbacks
   */
  @Input()
  beforeRender: AreaChartProps['beforeRender'];

  /**
   * {@inheritDoc  @sisense/sdk-ui!AreaChartProps.onDataReady}
   *
   * @category Callbacks
   */
  @Input()
  dataReady: AreaChartProps['dataReady'];

  /**
   * {@inheritDoc @sisense/sdk-ui!AreaChartProps.onDataPointClick}
   *
   * @category Callbacks
   */
  @Output()
  dataPointClick = new EventEmitter<DataPointEvent>();

  /**
   * {@inheritDoc @sisense/sdk-ui!AreaChartProps.onDataPointContextMenu}
   *
   * @category Callbacks
   */
  @Output()
  dataPointContextMenu = new EventEmitter<DataPointEvent>();

  /**
   * {@inheritDoc @sisense/sdk-ui!AreaChartProps.onDataPointsSelected}
   *
   * @category Callbacks
   */
  @Output()
  dataPointsSelect = new EventEmitter<DataPointsEvent>();

  /** @internal */
  public chartType: ChartType = 'area';
}

// packages/sdk-ui/src/area-chart.tsx
import { AreaChartProps } from './props';
import { Chart, shouldSkipSisenseContextWaiting } from './chart';
import { asSisenseComponent } from './decorators/component-decorators/as-sisense-component';
/**
 * A React component similar to a {@link LineChart},
 * but with filled in areas under each line and an option to display them as stacked.
 * More info on [Sisense Documentation page](https://docs.sisense.com/main/SisenseLinux/area-chart.htm).
 *
 * @example
 * An example of using the component to visualize the `Sample ECommerce` data source:
 * ```tsx
 * <AreaChart
 *   dataSet={DM.DataSource}
 *   dataOptions={{
 *     category: [DM.Commerce.Date.Years],
 *     value: [measureFactory.sum(DM.Commerce.Revenue)],
 *     breakBy: [DM.Commerce.Gender],
 *   }}
 *   styleOptions={{ subtype: 'area/stacked' }}
 *   filters={[filterFactory.members(DM.Commerce.Gender, ['Female', 'Male'])]}
 *   onDataPointClick={(point, nativeEvent) => {
 *     console.log('clicked', point, nativeEvent);
 *   }}
 * />
 * ```
 *
 * <img src="media://area-chart-example-1.png" width="800"/>
 * @param props - Area chart properties
 * @returns Area Chart component
 * @group Charts
 */
export const AreaChart = asSisenseComponent({
  componentName: 'AreaChart',
  shouldSkipSisenseContextWaiting,
})((props: AreaChartProps) => {
  return <Chart {...props} chartType="area" />;
});
