// packages/sdk-ui-angular/src/lib/components/scattermap-chart.component.ts
import { Component, Input } from '@angular/core';
import { type ChartType, type ScattermapChartProps } from '@sisense/sdk-ui-preact';

/**
 * An Angular component that allows to visualize geographical data as data points on a map.
 * See [Scattermap Chart](https://docs.sisense.com/main/SisenseLinux/scatter-map.htm) for more information.
 */
@Component({
  selector: 'csdk-scattermap-chart',
  template: `
    <csdk-chart
      [chartType]="chartType"
      [dataSet]="dataSet"
      [dataOptions]="dataOptions"
      [filters]="filters"
      [highlights]="highlights"
      [styleOptions]="styleOptions"
    />
  `,
})
export class ScattermapChartComponent {
  /**
   * {@inheritDoc @sisense/sdk-ui!ScattermapChartProps.dataSet}
   *
   * @category Data
   */
  @Input()
  dataSet: ScattermapChartProps['dataSet'];

  /**
   * {@inheritDoc @sisense/sdk-ui!ScattermapChartProps.dataOptions}
   *
   * @category Chart
   */
  @Input()
  dataOptions!: ScattermapChartProps['dataOptions'];

  /**
   * {@inheritDoc @sisense/sdk-ui!ScattermapChartProps.filters}
   *
   * @category Data
   */
  @Input()
  filters: ScattermapChartProps['filters'];

  /**
   * {@inheritDoc @sisense/sdk-ui!ScattermapChartProps.highlights}
   *
   * @category Data
   */
  @Input()
  highlights: ScattermapChartProps['highlights'];

  /**
   * {@inheritDoc @sisense/sdk-ui!ScattermapChartProps.styleOptions}
   *
   * @category Chart
   */
  @Input()
  styleOptions: ScattermapChartProps['styleOptions'];

  /** @internal */
  public chartType: ChartType = 'scattermap';
}

// packages/sdk-ui/src/scattermap-chart.tsx
import { ScattermapChartProps } from './props';
import { Chart, shouldSkipSisenseContextWaiting } from './chart';
import { asSisenseComponent } from './decorators/component-decorators/as-sisense-component';
/**
 * A React component that allows to visualize geographical data as data points on a map.
 * See [Scattermap Chart](https://docs.sisense.com/main/SisenseLinux/scatter-map.htm) for more information.
 *
 * @example
 * An example of using the component to visualize the `Sample ECommerce` data source:
 * ```tsx
 * <ScattermapChart
 *   dataSet={DM.DataSource}
 *   dataOptions={{
 *     locations: [DM.Country.Country],
 *     size: measureFactory.sum(DM.Commerce.Cost, 'Size by Cost'),
 *     colorBy: {
 *       column: measureFactory.sum(DM.Commerce.Revenue, 'Color by Revenue'),
 *       color: 'green'
 *     },
 *     details: DM.Category.Category,
 *   }}
 *   styleOptions={{
 *     markers: {
 *       fill: 'hollow-bold'
 *     }
 *   }}
 * />
 * ```
 *
 * <img src="media://scattermap-chart-example-1.png" width="600px" />
 * @param props - Scattermap chart properties
 * @returns Scattermap Chart component
 * @beta
 */
export const ScattermapChart = asSisenseComponent({
  componentName: 'ScattermapChart',
  shouldSkipSisenseContextWaiting,
})((props: ScattermapChartProps) => {
  return <Chart {...props} chartType="scattermap" />;
});
