// packages/sdk-ui-angular/src/lib/components/charts/indicator-chart.component.ts
import { Component, Input } from '@angular/core';
import { type ChartType } from '../../sdk-ui-core-exports';
import { type IndicatorChartProps } from '@sisense/sdk-ui-preact';

/**
 * A component that provides various options for displaying one or two numeric values as a number, gauge or ticker.
 *
 * @example
 * ```html
 *    <csdk-indicator-chart
 *      [dataSet]="indicator.dataSet"
 *      [dataOptions]="indicator.dataOptions"
 *      [filters]="filters"
 *      [styleOptions]="indicator.styleOptions"
 *    />
 * ```
 * ```ts
import { Component } from '@angular/core';
import { measureFactory, filterFactory } from '@sisense/sdk-data';
import * as DM from '../../assets/sample-healthcare-model';
import type { IndicatorStyleOptions } from '@sisense/sdk-ui-angular';

@Component({
  selector: 'app-analytics',
  templateUrl: './analytics.component.html',
  styleUrls: ['./analytics.component.scss'],
})
export class AnalyticsComponent {
  DM = DM;
  filters = [filterFactory.members(DM.Divisions.Divison_name, ['Cardiology', 'Neurology'])];
  indicator = {
    dataSet: DM.DataSource,
    dataOptions: {
      value: [measureFactory.sum(DM.Admissions.Cost_of_admission)],
      secondary: [measureFactory.sum(DM.Admissions.Diagnosis_ID)],
    },
    styleOptions: {
      indicatorComponents: {
        title: {
          shouldBeShown: true,
          text: 'Total Cost_of_admission',
        },
        secondaryTitle: {
          text: 'Total Diagnosis_ID',
        },
        ticks: {
          shouldBeShown: true,
        },
        labels: {
          shouldBeShown: true,
        },
      },
      subtype: 'indicator/gauge',
      skin: 2,
    } as IndicatorStyleOptions,
  };

}
 * ```
 * <img src="media://angular-indicator-chart-example.png" width="800px" />
 *
 * @group Charts
 */
@Component({
  selector: 'csdk-indicator-chart',
  template: `
    <csdk-chart
      [chartType]="chartType"
      [dataSet]="dataSet"
      [dataOptions]="dataOptions"
      [filters]="filters"
      [highlights]="highlights"
      [styleOptions]="styleOptions"
    />
  `,
})
export class IndicatorChartComponent {
  /**
   * {@inheritDoc @sisense/sdk-ui!IndicatorChartProps.dataSet}
   *
   * @category Data
   */
  @Input()
  dataSet: IndicatorChartProps['dataSet'];

  /**
   * {@inheritDoc @sisense/sdk-ui!IndicatorChartProps.dataOptions}
   *
   * @category Chart
   */
  @Input()
  dataOptions!: IndicatorChartProps['dataOptions'];

  /**
   * {@inheritDoc @sisense/sdk-ui!IndicatorChartProps.filters}
   *
   * @category Data
   */
  @Input()
  filters: IndicatorChartProps['filters'];

  /**
   * {@inheritDoc @sisense/sdk-ui!IndicatorChartProps.highlights}
   *
   * @category Data
   */
  @Input()
  highlights: IndicatorChartProps['highlights'];

  /**
   * {@inheritDoc @sisense/sdk-ui!IndicatorChartProps.styleOptions}
   *
   * @category Chart
   */
  @Input()
  styleOptions: IndicatorChartProps['styleOptions'];

  /**
   * {@inheritDoc  @sisense/sdk-ui!IndicatorChartProps.onDataReady}
   *
   * @category Callbacks
   * @internal
   */
  @Input()
  dataReady: IndicatorChartProps['onDataReady'];

  /** @internal */
  public chartType: ChartType = 'indicator';
}

// packages/sdk-ui/src/domains/visualizations/components/indicator-chart.tsx
import { asSisenseComponent } from '../../../infra/decorators/component-decorators/as-sisense-component';
import { IndicatorChartProps } from '../../../props';
import { Chart } from './chart';
import { shouldSkipSisenseContextWaiting } from './chart/helpers/should-skip-sisense-context-waiting';

/**
 * A React component that provides various options for displaying one or two numeric values as a number, gauge or ticker.
 *
 * @example
 * ```tsx
 * import { IndicatorChart } from '@sisense/sdk-ui';
 * import { measureFactory } from '@sisense/sdk-data';
 * import * as DM from './sample-ecommerce';
 *
 * const CodeExample = () => (
 *   <IndicatorChart
 *     dataSet={DM.DataSource}
 *     dataOptions={{
 *       value: [measureFactory.sum(DM.Commerce.Revenue, 'Total Revenue')],
 *       max: [measureFactory.constant(125000000)],
 *     }}
 *     styleOptions={{
 *       indicatorComponents: {
 *         title: { shouldBeShown: true, text: 'Total Revenue' },
 *         ticks: { shouldBeShown: false },
 *         labels: { shouldBeShown: true },
 *       },
 *       subtype: 'indicator/gauge',
 *       skin: 2,
 *     }}
 *   />
 * );
 *
 * export default CodeExample;
 * ```
 *
 * <img src="media://indicator-chart-example-1.png" width="400px" />
 *
 * Numeric indicator variant with a secondary value:
 *
 * ```tsx
 * <IndicatorChart
 *   dataSet={DM.DataSource}
 *   dataOptions={{
 *     value: [measureFactory.sum(DM.Commerce.Revenue, 'Total Revenue')],
 *     // secondary value is optional
 *     secondary: [measureFactory.sum(DM.Commerce.Quantity, 'Total Quantity')],
 *   }}
 * />
 * ```
 *
 * <img src="media://indicator-chart-example-3.png" width="400px" />
 *
 * Ticker style indicator variant:
 *
 * ```tsx
 * <IndicatorChart
 *   dataSet={DM.DataSource}
 *   dataOptions={{
 *     value: [measureFactory.sum(DM.Commerce.Revenue, 'Total Revenue')],
 *     max: [measureFactory.constant(125000000)],
 *   }}
 *   styleOptions={{
 *     indicatorComponents: {
 *       title: { shouldBeShown: true, text: 'Total Revenue' },
 *       ticks: { shouldBeShown: false },
 *       labels: { shouldBeShown: true },
 *     },
 *     subtype: 'indicator/gauge',
 *     skin: 2,
 *     forceTickerView: true,
 *     tickerBarHeight: 30,
 *     width: 400,
 *   }}
 * />
 * ```
 *
 * <img src="media://indicator-chart-example-4.png" width="400px" />
 * @param props - Indicator chart properties
 * @returns Indicator Chart component
 * @group Charts
 */
export const IndicatorChart = asSisenseComponent({
  componentName: 'IndicatorChart',
  shouldSkipSisenseContextWaiting,
})((props: IndicatorChartProps) => {
  return <Chart {...props} chartType="indicator" />;
});
