// packages/sdk-ui/src/indicator-chart.tsx
import { IndicatorChartProps } from './props';
import { Chart, shouldSkipSisenseContextWaiting } from './chart';
import { asSisenseComponent } from './decorators/component-decorators/as-sisense-component';
/**
 * A React component that provides various options for displaying one or two numeric values as a number, gauge or ticker.
 * See [Indicator](https://docs.sisense.com/main/SisenseLinux/indicator.htm) for more information.
 *
 * @example
 * An example of using the component to visualize the `Sample ECommerce` data source:
 * ```tsx
 * <IndicatorChart
 *   dataSet={DM.DataSource}
 *   dataOptions={{
 *     value: [
 *       {
 *         column: measures.sum(DM.Commerce.Revenue),
 *         numberFormatConfig: {
 *           name: 'Numbers',
 *           decimalScale: 2,
 *           trillion: true,
 *           billion: true,
 *           million: true,
 *           kilo: true,
 *           thousandSeparator: true,
 *           prefix: false,
 *           symbol: '$',
 *         },
 *       },
 *     ],
 *     secondary: [],
 *     min: [measures.constant(0)],
 *     max: [measures.constant(125000000)],
 *   }}
 *   filters={[filters.greaterThan(DM.Commerce.Revenue, 1000)]}
 *   styleOptions={{
 *     indicatorComponents: {
 *       title: {
 *         shouldBeShown: true,
 *         text: 'Total Revenue',
 *       },
 *       secondaryTitle: {
 *         text: '',
 *       },
 *       ticks: {
 *         shouldBeShown: true,
 *       },
 *       labels: {
 *         shouldBeShown: true,
 *       },
 *     },
 *     subtype: 'indicator/gauge',
 *     skin: 1,
 *   }}
 * />
 * ```
 *
 * <img src="media://indicator-chart-example-1.png" width="400px" />
 * @param props - Indicator chart properties
 * @returns Indicator Chart component
 */
export const IndicatorChart = asSisenseComponent({
  componentName: 'IndicatorChart',
  shouldSkipSisenseContextWaiting,
})((props: IndicatorChartProps) => {
  return <Chart {...props} chartType="indicator" />;
});

// packages/sdk-ui-angular/src/lib/components/indicator-chart.component.ts
import { Component, Input } from '@angular/core';
import { type ChartType, type IndicatorChartProps } from '@sisense/sdk-ui-preact';

/**
 * A component that provides various options for displaying one or two numeric values as a number, gauge or ticker.
 * See [Indicator](https://docs.sisense.com/main/SisenseLinux/indicator.htm) for more information.
 */
@Component({
  selector: 'csdk-indicator-chart',
  template: `
    <csdk-chart
      [chartType]="chartType"
      [dataSet]="dataSet"
      [dataOptions]="dataOptions"
      [filters]="filters"
      [highlights]="highlights"
    />
  `,
})
export class IndicatorChartComponent {
  /**
   * {@inheritDoc @sisense/sdk-ui!IndicatorChartProps.dataSet}
   *
   * @category Data
   */
  @Input()
  dataSet: IndicatorChartProps['dataSet'];

  /**
   * {@inheritDoc @sisense/sdk-ui!IndicatorChartProps.dataOptions}
   *
   * @category Chart
   */
  @Input()
  dataOptions!: IndicatorChartProps['dataOptions'];

  /**
   * {@inheritDoc @sisense/sdk-ui!IndicatorChartProps.filters}
   *
   * @category Data
   */
  @Input()
  filters: IndicatorChartProps['filters'];

  /**
   * {@inheritDoc @sisense/sdk-ui!IndicatorChartProps.highlights}
   *
   * @category Data
   */
  @Input()
  highlights: IndicatorChartProps['highlights'];

  /**
   * {@inheritDoc @sisense/sdk-ui!IndicatorChartProps.styleOptions}
   *
   * @category Chart
   */
  @Input()
  styleOptions: IndicatorChartProps['styleOptions'];

  /** @internal */
  public chartType: ChartType = 'indicator';
}
