// packages/sdk-ui-angular/src/lib/components/charts/pivot-table.component.ts
import {
  AfterViewInit,
  Component,
  ElementRef,
  Input,
  OnChanges,
  OnDestroy,
  ViewChild,
} from '@angular/core';
import {
  PivotTable,
  ComponentAdapter,
  createElement,
  type PivotTableProps as PivotTablePropsPreact,
} from '@sisense/sdk-ui-preact';
import { SisenseContextService } from '../../services';
import { ThemeService } from '../../services';
import {
  createSisenseContextConnector,
  createThemeContextConnector,
} from '../../component-wrapper-helpers';
import { template, rootId } from '../../component-wrapper-helpers/template';

export interface PivotTableProps extends PivotTablePropsPreact {}

/**
 * Pivot Table with and pagination.
 *
 * @example
 * ```html
 *  <csdk-pivot-table
 *    [dataSet]="pivotTable.dataSet"
 *    [dataOptions]="pivotTable.dataOptions"
 *    [filters]="pivotTable.filters"
 *    [styleOptions]="pivotTable.styleOptions"
 *  />
 * ```
 * ```ts
import { Component } from '@angular/core';
import { measureFactory, filterFactory } from '@sisense/sdk-data';
import * as DM from '../../assets/sample-ecommerce';
import type { PivotTableDataOptions } from '@sisense/sdk-ui-angular';

@Component({
  selector: 'app-analytics',
  templateUrl: './analytics.component.html',
  styleUrls: ['./analytics.component.scss'],
})
export class AnalyticsComponent {

  pivotTableDataOptions: PivotTableDataOptions = {
    rows: [
      { column: DM.Category.Category, includeSubTotals: true },
      { column: DM.Commerce.AgeRange, includeSubTotals: true },
      DM.Commerce.Condition,
    ],
    columns: [{ column: DM.Commerce.Gender, includeSubTotals: true }],
    values: [
      measureFactory.sum(DM.Commerce.Cost, 'Total Cost'),
      {
        column: measureFactory.sum(DM.Commerce.Revenue, 'Total Revenue'),
        totalsCalculation: 'sum',
        dataBars: true,
      },
    ],
    grandTotals: { title: 'Grand Total', rows: true, columns: true },
  };

  pivotTable = {
    dataSet: DM.DataSource,
    dataOptions: this.pivotTableDataOptions,
    filters: [filterFactory.members(DM.Commerce.Gender, ['Female', 'Male'])],
    styleOptions: { width: 1400, height: 600, rowsPerPage: 50 },
  };

}
 * ```
 * <img src="media://angular-pivot-table-example.png" width="800px" />
 * @group Data Grids
 * @beta
 */
@Component({
  selector: 'csdk-pivot-table',
  template,
})
export class PivotTableComponent implements AfterViewInit, OnChanges, OnDestroy {
  /** @internal */
  @ViewChild(rootId)
  preactRef!: ElementRef<HTMLDivElement>;

  /**
   * {@inheritDoc @sisense/sdk-ui!PivotTableProps.dataSet}
   *
   * @category Data
   */
  @Input()
  dataSet: PivotTableProps['dataSet'];

  /**
   * {@inheritDoc @sisense/sdk-ui!PivotTableProps.dataOptions}
   *
   * @category Data
   */
  @Input()
  dataOptions!: PivotTableProps['dataOptions'];

  /**
   * {@inheritDoc @sisense/sdk-ui!PivotTableProps.filters}
   *
   * @category Data
   */
  @Input()
  filters: PivotTableProps['filters'];

  /**
   * {@inheritDoc @sisense/sdk-ui!PivotTableProps.highlights}
   *
   * @category Data
   */
  @Input()
  highlights: PivotTableProps['highlights'];

  /**
   * {@inheritDoc @sisense/sdk-ui!PivotTableProps.styleOptions}
   *
   * @category Representation
   */
  @Input()
  styleOptions: PivotTableProps['styleOptions'];

  private componentAdapter: ComponentAdapter;

  constructor(
    private sisenseContextService: SisenseContextService,
    private themeService: ThemeService,
  ) {
    this.componentAdapter = new ComponentAdapter(
      () => this.createPreactComponent(),
      [
        createSisenseContextConnector(this.sisenseContextService),
        createThemeContextConnector(this.themeService),
      ],
    );
  }

  /** @internal */
  ngAfterViewInit() {
    this.componentAdapter.render(this.preactRef.nativeElement);
  }

  /** @internal */
  ngOnChanges() {
    if (this.preactRef) {
      this.componentAdapter.render(this.preactRef.nativeElement);
    }
  }

  private createPreactComponent() {
    const props = {
      dataSet: this.dataSet,
      dataOptions: this.dataOptions,
      filters: this.filters,
      highlights: this.highlights,
      styleOptions: this.styleOptions,
    };

    return createElement(PivotTable, props);
  }

  /** @internal */
  ngOnDestroy() {
    this.componentAdapter.destroy();
  }
}

// packages/sdk-ui/src/pivot-table/pivot-table.tsx
import React, { useEffect, useRef } from 'react';
import { PivotTableProps } from '../props';
import { asSisenseComponent } from '../decorators/component-decorators/as-sisense-component';
import { shouldSkipSisenseContextWaiting } from '../chart';
import { useSisenseContext } from '../sisense-context/sisense-context';
import { useGetPivotTableQuery } from './use-get-pivot-table-query';

const DEFAULT_TABLE_ROWS_PER_PAGE = 25 as const;

/**
 * Pivot Table with pagination.
 *
 * See [Pivot Tables](https://docs.sisense.com/main/SisenseLinux/pivot.htm) for more information.
 *
 * @example
 * (1) Example of PivotTable from the `Sample ECommerce` data model:
 *
 * ```tsx
 * <PivotTable
 *   dataSet={DM.DataSource}
 *   dataOptions={{
 *     rows: [
 *       { column: DM.Category.Category, includeSubTotals: true },
 *       { column: DM.Commerce.AgeRange, includeSubTotals: true },
 *       DM.Commerce.Condition,
 *     ],
 *     columns: [{ column: DM.Commerce.Gender, includeSubTotals: true }],
 *     values: [
 *       {
 *         column: measureFactory.sum(DM.Commerce.Cost, 'Total Cost'),
 *         dataBars: true,
 *         totalsCalculation: 'sum',
 *       },
 *       {
 *         column: measureFactory.sum(DM.Commerce.Revenue, 'Total Revenue'),
 *         totalsCalculation: 'sum',
 *       },
 *     ],
 *     grandTotals: { title: 'Grand Total', rows: true, columns: true },
 *   }}
 *   filters={[filterFactory.members(DM.Commerce.Gender, ['Female', 'Male'])]}
 *   styleOptions={{ width: 1000, height: 600, rowsPerPage: 50 }}
 * />
 * ```
 * @param props - Pivot Table properties
 * @returns Pivot Table component
 * @group Data Grids
 * @alpha
 */

export const PivotTable = asSisenseComponent({
  componentName: 'PivotTable',
  shouldSkipSisenseContextWaiting,
})((pivotTableProps: PivotTableProps) => {
  // retrieve and validate the pivot client
  const { app } = useSisenseContext();
  const pivotClient = app?.pivotClient;
  if (!pivotClient) {
    throw new Error('Pivot client not initialized');
  }

  const { styleOptions = {} } = pivotTableProps;
  // get the jaql from the pivot table props
  const { isError, error, jaql } = useGetPivotTableQuery(pivotTableProps);

  if (isError) {
    throw error;
  }

  const nodeRef = useRef<HTMLDivElement>(null);
  const pivotBuilder = pivotClient.preparePivotBuilder();

  useEffect(() => {
    if (nodeRef.current && jaql) {
      const {
        rowsPerPage = DEFAULT_TABLE_ROWS_PER_PAGE,
        width = 400,
        height = 400,
        isAutoHeight = false,
      } = styleOptions;
      const props = {
        width,
        height,
        isAutoHeight,
        isPaginated: true,
        itemsPerPage: rowsPerPage,
      };

      pivotBuilder.render(nodeRef.current, props);
      pivotBuilder.updateJaql(jaql);
    }

    return () => {
      // for cleanup if needed
    };
  }, [jaql, pivotBuilder, pivotClient, styleOptions]);

  return <div ref={nodeRef} aria-label="pivot-table-root" />;
});
