// packages/sdk-ui-angular/src/lib/components/widgets/dashboard-widget.component.ts
import {
  AfterViewInit,
  Component,
  ElementRef,
  Input,
  OnChanges,
  OnDestroy,
  ViewChild,
} from '@angular/core';
import {
  DashboardWidget,
  type DashboardWidgetProps,
  ComponentAdapter,
  createElement,
} from '@sisense/sdk-ui-preact';
import { SisenseContextService } from '../../services/sisense-context.service';
import { ThemeService } from '../../services/theme.service';
import {
  createSisenseContextConnector,
  createThemeContextConnector,
} from '../../component-wrapper-helpers';
import { template, rootId } from '../../component-wrapper-helpers/template';

/**
 * The Dashboard Widget component, which is a thin wrapper on {@link ChartWidgetComponent},
 * is used to render a widget created in a Sisense Fusion instance.
 *
 * To learn more about using Sisense Fusion Widgets in Compose SDK, see
 * [Sisense Fusion Widgets](https://sisense.dev/guides/sdk/guides/charts/guide-fusion-widgets.html).
 *
 * @example
 * ```html
 * <csdk-dashboard-widget
 *    [widgetOid]="widgetOid"
 *    [dashboardOid]="dashboardOid"
 *    [includeDashboardFilters]="true"
 * />
 * ```
 * ```ts
 * import { Component } from '@angular/core';
 * import { ChartType } from '@sisense/sdk-ui-angular';
 * import { filterFactory, measureFactory } from '@sisense/sdk-data';
 * import * as DM from '../../assets/sample-healthcare-model';
 *
 * @Component({
 *  selector: 'app-widgets',
 *  templateUrl: './widgets.component.html',
 *  styleUrls: ['./widgets.component.scss'],
 * })
 * export class WidgetsComponent {
 *  widgetOid: string = '60f3e3e3e4b0e3e3e4b0e3e3';
 *  dashboardOid: string = '60f3e3e3e4b0e3e3e4b0e3e3';
 * }
 * ```
 * @group Fusion Embed
 * @fusionEmbed
 */
@Component({
  selector: 'csdk-dashboard-widget',
  template,
})
export class DashboardWidgetComponent implements AfterViewInit, OnChanges, OnDestroy {
  /** @internal */
  @ViewChild(rootId)
  preactRef!: ElementRef<HTMLDivElement>;

  /**
   * {@inheritDoc @sisense/sdk-ui!DashboardWidgetProps.widgetOid}
   *
   * @category Widget
   */
  @Input()
  widgetOid!: DashboardWidgetProps['widgetOid'];

  /**
   * {@inheritDoc @sisense/sdk-ui!DashboardWidgetProps.dashboardOid}
   *
   * @category Widget
   */
  @Input()
  dashboardOid!: DashboardWidgetProps['dashboardOid'];

  /**
   * {@inheritDoc @sisense/sdk-ui!DashboardWidgetProps.filters}
   *
   * @category Data
   */
  @Input()
  filters: DashboardWidgetProps['filters'];

  /**
   * {@inheritDoc @sisense/sdk-ui!DashboardWidgetProps.highlights}
   *
   * @category Data
   */
  @Input()
  highlights: DashboardWidgetProps['highlights'];

  /**
   * {@inheritDoc @sisense/sdk-ui!DashboardWidgetProps.filtersMergeStrategy}
   *
   * @category Data
   */
  @Input()
  filtersMergeStrategy: DashboardWidgetProps['filtersMergeStrategy'];

  /**
   * {@inheritDoc @sisense/sdk-ui!DashboardWidgetProps.includeDashboardFilters}
   *
   * @category Data
   */
  @Input()
  includeDashboardFilters: DashboardWidgetProps['includeDashboardFilters'];

  /**
   * {@inheritDoc @sisense/sdk-ui!DashboardWidgetProps.title}
   *
   * @category Widget
   */
  @Input()
  title: DashboardWidgetProps['title'];

  /**
   * {@inheritDoc @sisense/sdk-ui!DashboardWidgetProps.description}
   *
   * @category Widget
   */
  @Input()
  description: DashboardWidgetProps['description'];

  /**
   * {@inheritDoc @sisense/sdk-ui!DashboardWidgetProps.styleOptions}
   *
   * @category Widget
   */
  @Input()
  styleOptions: DashboardWidgetProps['styleOptions'];

  /**
   * {@inheritDoc @sisense/sdk-ui!DashboardWidgetProps.highlightSelectionDisabled}
   *
   * @category Widget
   */
  @Input()
  highlightSelectionDisabled: DashboardWidgetProps['highlightSelectionDisabled'];

  /** @internal */
  @Input()
  drilldownOptions: DashboardWidgetProps['drilldownOptions'];

  private componentAdapter: ComponentAdapter;

  constructor(
    private sisenseContextService: SisenseContextService,
    private themeService: ThemeService,
  ) {
    this.componentAdapter = new ComponentAdapter(
      () => this.createPreactComponent(),
      [
        createSisenseContextConnector(this.sisenseContextService),
        createThemeContextConnector(this.themeService),
      ],
    );
  }

  /** @internal */
  ngAfterViewInit() {
    this.componentAdapter.render(this.preactRef.nativeElement);
  }

  /** @internal */
  ngOnChanges() {
    if (this.preactRef) {
      this.componentAdapter.render(this.preactRef.nativeElement);
    }
  }

  /** @internal */
  private createPreactComponent() {
    const props = {
      widgetOid: this.widgetOid,
      dashboardOid: this.dashboardOid,
      filters: this.filters,
      highlights: this.highlights,
      filtersMergeStrategy: this.filtersMergeStrategy,
      includeDashboardFilters: this.includeDashboardFilters,
      title: this.title,
      description: this.description,
      styleOptions: this.styleOptions,
      highlightSelectionDisabled: this.highlightSelectionDisabled,
      drilldownOptions: this.drilldownOptions,
    };

    return createElement(DashboardWidget, props);
  }

  /** @internal */
  ngOnDestroy() {
    this.componentAdapter.destroy();
  }
}

// packages/sdk-ui/src/dashboard-widget/dashboard-widget.tsx
/* eslint-disable max-lines-per-function */
import React, { useMemo, type FunctionComponent } from 'react';
import { type Filter } from '@sisense/sdk-data';
import { ChartWidget } from '../widgets/chart-widget';
import { TableWidget } from '../widgets/table-widget';
import { ChartWidgetProps, DashboardWidgetProps, TableWidgetProps } from '../props';
import { useThemeContext } from '../theme-provider';
import { asSisenseComponent } from '../decorators/component-decorators/as-sisense-component';
import {
  convertFilterRelationsModelToJaql,
  getFilterRelationsFromJaql,
  isTabularWidget,
  mergeFilters,
  mergeFiltersByStrategy,
} from './utils';
import { extractDashboardFiltersForWidget } from './translate-dashboard-filters';
import { useFetchWidgetDtoModel } from './use-fetch-widget-dto-model';
import { WidgetModel } from '../models';

/**
 * The Dashboard Widget component, which is a thin wrapper on the {@link ChartWidget} component,
 * is used to render a widget created in a Sisense Fusion instance.
 *
 * To learn more about using Sisense Fusion Widgets in Compose SDK,
 * see [Sisense Fusion Widgets](/guides/sdk/guides/charts/guide-fusion-widgets.html).
 *
 * ## Example
 *
 * Display two dashboard widgets from a Fusion Embed instance.
 *
 * <iframe
 *  src='https://csdk-playground.sisense.com/?example=fusion-assets%2Ffusion-widgets&mode=docs'
 *  width=800
 *  height=870
 *  style='border:none;'
 * />
 *
 * @group Fusion Embed
 * @fusionEmbed
 */
export const DashboardWidget: FunctionComponent<DashboardWidgetProps> = asSisenseComponent({
  componentName: 'DashboardWidget',
  customContextErrorMessageKey: 'errors.dashboardWidgetNoSisenseContext',
})((props) => {
  const { widgetOid, dashboardOid, includeDashboardFilters, ...restProps } = props;
  const { themeSettings } = useThemeContext();
  const {
    widget: fetchedWidget,
    dashboard: fetchedDashboard,
    error: fetchError,
  } = useFetchWidgetDtoModel({
    widgetOid,
    dashboardOid,
    includeDashboard: includeDashboardFilters,
  });

  if (fetchError) throw fetchError;

  const { widgetType, props: fetchedProps } = useMemo(() => {
    if (!fetchedWidget) {
      return { widgetType: null, props: null };
    }

    const widgetModel = new WidgetModel(fetchedWidget, themeSettings);
    const extractedWidgetProps = {
      props: isTabularWidget(widgetModel.widgetType)
        ? widgetModel.getTableWidgetProps()
        : widgetModel.getChartWidgetProps(),
      widgetType: widgetModel.widgetType,
    };

    if (includeDashboardFilters) {
      const { filters: dashboardFilters, highlights: dashboardHighlights } =
        extractDashboardFiltersForWidget(fetchedDashboard!, fetchedWidget);

      extractedWidgetProps.props.filters = mergeFilters(
        dashboardFilters,
        extractedWidgetProps.props.filters as Filter[],
      );
      (extractedWidgetProps.props as ChartWidgetProps).highlights = dashboardHighlights;
    }

    return extractedWidgetProps;
  }, [fetchedWidget, fetchedDashboard, themeSettings, includeDashboardFilters]);

  // if filter relations are set on dashboard widget, additionally provided filters will be ignored
  // since there is not enough information how to merge them
  const filters = mergeFiltersByStrategy(
    fetchedProps?.filters as Filter[],
    restProps.filters,
    restProps.filtersMergeStrategy,
  );

  const highlights = mergeFiltersByStrategy(
    (fetchedProps as ChartWidgetProps)?.highlights,
    restProps.highlights,
    restProps.filtersMergeStrategy,
  );

  if (!fetchedProps) {
    return null;
  }
  const filterRelations = getFilterRelationsFromJaql(
    filters,
    convertFilterRelationsModelToJaql(
      fetchedDashboard?.filterRelations?.length
        ? fetchedDashboard?.filterRelations[0].filterRelations
        : undefined,
    ),
  );

  return isTabularWidget(widgetType) ? (
    <TableWidget
      {...(fetchedProps as TableWidgetProps)}
      {...restProps}
      filters={filterRelations}
      styleOptions={{
        ...fetchedProps.styleOptions,
        ...props.styleOptions,
      }}
    />
  ) : (
    <ChartWidget
      {...(fetchedProps as ChartWidgetProps)}
      {...restProps}
      filters={filterRelations}
      highlights={highlights}
      drilldownOptions={{
        ...(fetchedProps as ChartWidgetProps).drilldownOptions,
        ...props.drilldownOptions,
      }}
      styleOptions={{
        ...fetchedProps.styleOptions,
        ...props.styleOptions,
      }}
    />
  );
});
