// packages/sdk-ui-angular/src/lib/components/dashboard-widget.component.ts
import {
  AfterViewInit,
  Component,
  ElementRef,
  Input,
  OnChanges,
  OnDestroy,
  ViewChild,
} from '@angular/core';
import {
  DashboardWidget,
  type DashboardWidgetProps,
  ComponentAdapter,
  createElement,
} from '@sisense/sdk-ui-preact';
import { SisenseContextService } from '../services/sisense-context.service';
import { ThemeService } from '../services/theme.service';
import {
  createSisenseContextConnector,
  createThemeContextConnector,
} from '../component-wrapper-helpers';
import { template, rootId } from '../component-wrapper-helpers/template';

/**
 * The Dashboard Widget component, which is a thin wrapper on {@link ChartWidgetComponent},
 * is used to render a widget created in a Sisense Fusion instance.
 *
 * To learn more about using Sisense Fusion Widgets in Compose SDK, see
 * [Sisense Fusion Widgets](https://sisense.dev/guides/sdk/guides/charts/guide-fusion-widgets.html).
 *
 */
@Component({
  selector: 'csdk-dashboard-widget',
  template,
})
export class DashboardWidgetComponent implements AfterViewInit, OnChanges, OnDestroy {
  /** @internal */
  @ViewChild(rootId)
  preactRef!: ElementRef<HTMLDivElement>;

  @Input()
  widgetOid!: DashboardWidgetProps['widgetOid'];

  @Input()
  dashboardOid!: DashboardWidgetProps['dashboardOid'];

  /**
   * {@inheritDoc @sisense/sdk-ui!ChartProps.filters}
   *
   * @category Data
   */
  @Input()
  filters: DashboardWidgetProps['filters'];

  @Input()
  highlights: DashboardWidgetProps['highlights'];

  @Input()
  filtersMergeStrategy: DashboardWidgetProps['filtersMergeStrategy'];

  @Input()
  includeDashboardFilters: DashboardWidgetProps['includeDashboardFilters'];

  @Input()
  title: DashboardWidgetProps['title'];

  @Input()
  description: DashboardWidgetProps['description'];

  /**
   * {@inheritDoc @sisense/sdk-ui!DashboardWidgetProps.styleOptions}
   *
   * @category Widget
   */
  @Input()
  styleOptions: DashboardWidgetProps['styleOptions'];

  @Input()
  highlightSelectionDisabled: DashboardWidgetProps['highlightSelectionDisabled'];

  /** @internal */
  @Input()
  drilldownOptions: DashboardWidgetProps['drilldownOptions'];

  private componentAdapter: ComponentAdapter;

  constructor(
    private sisenseContextService: SisenseContextService,
    private themeService: ThemeService,
  ) {
    this.componentAdapter = new ComponentAdapter(
      () => this.createPreactComponent(),
      [
        createSisenseContextConnector(this.sisenseContextService),
        createThemeContextConnector(this.themeService),
      ],
    );
  }

  /** @internal */
  ngAfterViewInit() {
    this.componentAdapter.render(this.preactRef.nativeElement);
  }

  /** @internal */
  ngOnChanges() {
    if (this.preactRef) {
      this.componentAdapter.render(this.preactRef.nativeElement);
    }
  }

  /** @internal */
  private createPreactComponent() {
    const props = {
      widgetOid: this.widgetOid,
      dashboardOid: this.dashboardOid,
      filters: this.filters,
      highlights: this.highlights,
      filtersMergeStrategy: this.filtersMergeStrategy,
      includeDashboardFilters: this.includeDashboardFilters,
      title: this.title,
      description: this.description,
      styleOptions: this.styleOptions,
      highlightSelectionDisabled: this.highlightSelectionDisabled,
      drilldownOptions: this.drilldownOptions,
    };

    return createElement(DashboardWidget, props);
  }

  /** @internal */
  ngOnDestroy() {
    this.componentAdapter.destroy();
  }
}

// packages/sdk-ui/src/widget-by-id/dashboard-widget.tsx
import { type FunctionComponent } from 'react';
import { DashboardWidgetProps } from '../props.js';
import { WidgetById } from './widget-by-id.js';

/**
 * The Dashboard Widget component, which is a thin wrapper on the {@link ChartWidget} component,
 * is used to render a widget created in a Sisense Fusion instance.
 *
 * To learn more about using Sisense Fusion Widgets in Compose SDK,
 * see [Sisense Fusion Widgets](/guides/sdk/guides/charts/guide-fusion-widgets.html).
 *
 * **Note:** Widget extensions based on JS scripts and add-ons in Fusion are not supported.
 *
 * ## Example
 *
 * Display two dashboard widgets from a Fusion instance.
 *
 * <iframe
 *  src='https://csdk-playground.sisense.com/?example=fusion-assets%2Ffusion-widgets&mode=docs'
 *  width=800
 *  height=870
 *  style='border:none;'
 * />
 *
 * @group Fusion Assets
 * @fusionEmbed
 * @deprecated Use {@link @sisense/sdk-ui!WidgetById | `WidgetById`} instead.
 */
export const DashboardWidget = WidgetById as FunctionComponent<DashboardWidgetProps>;
