// packages/sdk-ui-angular/src/lib/components/widgets/drilldown-widget.component.ts
import {
  AfterViewInit,
  Component,
  ElementRef,
  EventEmitter,
  Input,
  OnChanges,
  OnDestroy,
  Output,
  ViewChild,
} from '@angular/core';
import {
  ComponentAdapter,
  createElement,
  DrilldownWidget,
  type DrilldownWidgetProps,
  type ContextMenuProps,
  type CustomDrilldownResult as CustomDrilldownResultBase,
  type ComponentRenderer,
  DrilldownBreadcrumbsProps,
  createWrapperElement,
  createWrapperElementHandler,
  createComponentRenderer,
} from '@sisense/sdk-ui-preact';
import { SisenseContextService } from '../../services/sisense-context.service';
import { ThemeService } from '../../services/theme.service';
import type { Arguments } from '../../types/utility-types';
import {
  createSisenseContextConnector,
  createThemeContextConnector,
} from '../../component-wrapper-helpers';
import {
  templateWithContent,
  rootId,
  rootContentId,
} from '../../component-wrapper-helpers/template';

export type CustomDrilldownResult = CustomDrilldownResultBase & {
  breadcrumbsComponent?: {
    render: ComponentRenderer;
  };
};

/**
 * An Angular component designed to add drilldown functionality to any type of chart.
 *
 * It acts as a wrapper around a given chart component, enhancing it with drilldown capabilities
 *
 * The widget offers several features including:
 * - A context menu for initiating drilldown actions (can be provided as a custom component)
 * - Breadcrumbs that not only allow for drilldown selection slicing but also
 * provide an option to clear the selection (can be provided as a custom component)
 * - Filters specifically created for drilldown operation
 * - An option to navigate to the next drilldown dimension
 *
 * When an `initialDimension` is specified, the `drilldownDimension` will automatically inherit its value,
 * even before any points on the chart are selected.
 * This allows for complete control over the chart's dimensions to be handed over to the DrilldownWidget
 *
 * @example
 * An example of using the `csdk-drilldown-widget` component to plot a `csdk-column-chart`
 * over the Sample Healthcare data source hosted in a Sisense instance:
 * ```ts
 * // Component behavior in .component.ts
 * chart = {
 *   dataOptions: {
 *     category: [DM.Divisions.Divison_name],
 *     value: [measureFactory.sum(DM.Admissions.Cost_of_admission)],
 *     breakBy: [],
 *   },
 *   dataPointContextMenu: ({ point, nativeEvent }: { point: any; nativeEvent: MouseEvent }) => {
 *     this.drilldownResult?.onDataPointsSelected?.([point], nativeEvent);
 *     this.drilldownResult?.onContextMenu({
 *       left: nativeEvent.clientX,
 *       top: nativeEvent.clientY,
 *     });
 *   }
 * }
 *
 * drilldownResult?: CustomDrilldownResult;
 *
 * drilldown = {
 *   drilldownDimensions: [DM.Patients.Gender, DM.Admissions.Surgical_Procedure],
 *   initialDimension: DM.Divisions.Divison_name,
 *   drilldownChange: (drilldownResult: CustomDrilldownResult) => {
 *     this.drilldownResult = drilldownResult;
 *     this.chart.dataOptions = {
 *       ...this.chart.dataOptions,
 *       category: [drilldownResult.drilldownDimension]
 *     }
 *   }
 * };
 * ```
 * ```html
 * <!--Component HTML template in .component.html-->
 * <csdk-drilldown-widget
 *   [drilldownDimensions]="drilldown.drilldownDimensions"
 *   [initialDimension]="drilldown.initialDimension"
 *   (drilldownResultChange)="drilldown.drilldownChange($event)"
 * >
 *   <csdk-column-chart
 *     [dataSet]="DM.DataSource"
 *     [dataOptions]="chart.dataOptions"
 *     [filters]="drilldownResult?.drilldownFilters || []"
 *     (dataPointContextMenu)="chart.dataPointContextMenu($event)"
 *   />
 * </csdk-drilldown-widget>
 * ```
 * <img src="media://angular-drilldown-widget-example.png" width="800px" />
 *
 * @group Drilldown
 */
@Component({
  selector: 'csdk-drilldown-widget',
  template: templateWithContent,
})
export class DrilldownWidgetComponent implements AfterViewInit, OnChanges, OnDestroy {
  /**
   * @internal
   */
  @ViewChild(rootId)
  preactRef!: ElementRef<HTMLDivElement>;

  /**
   * @internal
   */
  @ViewChild(rootContentId)
  preactContentRef!: ElementRef<HTMLDivElement>;

  /**
   * {@inheritDoc @sisense/sdk-ui!DrilldownWidgetProps.drilldownDimensions}
   */
  @Input()
  drilldownDimensions!: DrilldownWidgetProps['drilldownDimensions'];

  /**
   * {@inheritDoc @sisense/sdk-ui!DrilldownWidgetProps.initialDimension}
   */
  @Input()
  initialDimension!: DrilldownWidgetProps['initialDimension'];

  @Input()
  config?: Omit<DrilldownWidgetProps['config'], 'breadcrumbsComponent | contextMenuComponent'> & {
    breadcrumbsComponent?: (drilldownBreadcrumbsProps: DrilldownBreadcrumbsProps) => HTMLDivElement;
    contextMenuComponent?: (contextMenuProps: ContextMenuProps) => HTMLDivElement;
  };

  @Output()
  drilldownResultChange = new EventEmitter<CustomDrilldownResult>();

  private componentAdapter: ComponentAdapter;

  /**
   * Constructor for the `DrilldownWidgetComponent`.
   *
   * @param sisenseContextService - Sisense context service
   * @param themeService - Theme service
   */
  constructor(
    /**
     * Sisense context service
     *
     * @category Constructor
     */
    public sisenseContextService: SisenseContextService,
    /**
     * Theme service
     *
     * @category Constructor
     */
    public themeService: ThemeService,
  ) {
    this.componentAdapter = new ComponentAdapter(
      () => this.createPreactComponent(),
      [
        createSisenseContextConnector(this.sisenseContextService),
        createThemeContextConnector(this.themeService),
      ],
    );
  }

  /**
   * @internal
   */
  ngAfterViewInit() {
    this.componentAdapter.render(this.preactRef.nativeElement);
  }

  /**
   * @internal
   */
  ngOnChanges() {
    if (this.preactRef) {
      this.componentAdapter.render(this.preactRef.nativeElement);
    }
  }

  private createPreactComponent() {
    const props = {
      drilldownDimensions: this.drilldownDimensions,
      initialDimension: this.initialDimension,
      config: {
        ...this.config,
        ...(this.config?.breadcrumbsComponent && {
          breadcrumbsComponent: createWrapperElementHandler(this.config.breadcrumbsComponent),
        }),
        ...(this.config?.contextMenuComponent && {
          contextMenuComponent: (contextMenuProps: ContextMenuProps) =>
            createWrapperElement(this.config!.contextMenuComponent!(contextMenuProps)),
        }),
      },
    } as DrilldownWidgetProps;

    return createElement(
      DrilldownWidget,
      props,
      (customDrilldownResult: Arguments<DrilldownWidgetProps['children']>[0]) => {
        const { breadcrumbsComponent } = customDrilldownResult;
        this.drilldownResultChange.emit({
          ...customDrilldownResult,
          ...(breadcrumbsComponent && {
            breadcrumbsComponent: { render: createComponentRenderer(breadcrumbsComponent) },
          }),
        } as CustomDrilldownResult);
        return createWrapperElement(this.preactContentRef.nativeElement);
      },
    );
  }

  /**
   * @internal
   */
  ngOnDestroy() {
    this.componentAdapter.destroy();
  }
}

// packages/sdk-ui/src/widgets/drilldown-widget.tsx
/* eslint-disable max-lines-per-function */

import { useState, useCallback, useMemo } from 'react';
import { Attribute } from '@sisense/sdk-data';
import { DataPoint, MenuPosition, MenuItemSection } from '../types';
import { ContextMenu } from './common/context-menu';
import { DrilldownBreadcrumbs } from './common/drilldown-breadcrumbs';
import { useCustomDrilldown } from './common/custom-drilldown';
import { DrilldownWidgetProps } from '../props';

/**
 * React component designed to add drilldown functionality to any type of chart
 *
 * It acts as a wrapper around a given chart component, enhancing it with drilldown capabilities
 *
 * The widget offers several features including:
 * - A context menu for initiating drilldown actions (can be provided as a custom component)
 * - Breadcrumbs that not only allow for drilldown selection slicing but also
 * provide an option to clear the selection (can be provided as a custom component)
 * - Filters specifically created for drilldown operation
 * - An option to navigate to the next drilldown dimension
 *
 * When an `initialDimension` is specified, the `drilldownDimension` will automatically inherit its value,
 * even before any points on the chart are selected.
 * This allows for complete control over the chart's dimensions to be handed over to the DrilldownWidget
 *
 * @example
 * Example of using the `DrilldownWidget` component to
 * plot a custom React component that uses the `ExecuteQuery` component to
 * query the `Sample ECommerce` data source hosted in a Sisense instance.
 * ```tsx
 * <DrilldownWidget
 *   drilldownDimensions={[DM.Commerce.AgeRange, DM.Commerce.Gender, DM.Commerce.Condition]}
 *   initialDimension={DM.Category.Category}
 * >
 *   {({ drilldownFilters, drilldownDimension, onDataPointsSelected, onContextMenu }) => (
 *     <ExecuteQuery
 *       dataSource={DM.DataSource}
 *       dimensions={[drilldownDimension]}
 *       measures={measure.sum(DM.Commerce.Revenue)}
 *       filters={drilldownFilters}
 *     >
 *       {(data) => (
 *         <MyCustomChart
 *           rawData={data}
 *           onContextMenu={onContextMenu}
 *           onDataPointsSelected={onDataPointsSelected}
 *         />
 *       )}
 *     </ExecuteQuery>
 *   )}
 * </DrilldownWidget>
 * ```
 * @param props - DrilldownWidget properties
 * @returns DrilldownWidget wrapper component
 */
export const DrilldownWidget = ({
  drilldownDimensions,
  initialDimension,
  config,
  children,
}: DrilldownWidgetProps) => {
  const [selectedDataPoints, setSelectedDataPoints] = useState<DataPoint[]>([]);
  const [contextMenuPos, setContextMenuPos] = useState<null | MenuPosition>(null);

  const ContextMenuComponent = config?.contextMenuComponent ?? ContextMenu;
  const BreadcrumbsComponent = config?.breadcrumbsComponent ?? DrilldownBreadcrumbs;

  const {
    selectDrilldown,
    sliceDrilldownSelections,
    clearDrilldownSelections,
    availableDrilldowns,
    drilldownFilters,
    drilldownFiltersDisplayValues,
    drilldownDimension,
  } = useCustomDrilldown({
    drilldownDimensions,
    initialDimension,
  });

  const breadcrumbs = useMemo(() => {
    return (
      drilldownDimension && (
        <BreadcrumbsComponent
          filtersDisplayValues={drilldownFiltersDisplayValues}
          currentDimension={drilldownDimension}
          clearDrilldownSelections={clearDrilldownSelections}
          sliceDrilldownSelections={sliceDrilldownSelections}
        />
      )
    );
  }, [
    BreadcrumbsComponent,
    clearDrilldownSelections,
    drilldownDimension,
    drilldownFiltersDisplayValues,
    sliceDrilldownSelections,
  ]);

  const openContextMenu = (menuPos: { top: number; left: number }) => {
    setContextMenuPos(menuPos);
  };

  const closeContextMenu = useCallback(() => {
    setSelectedDataPoints([]);
    setContextMenuPos(null);
  }, [setSelectedDataPoints]);

  const onMenuDrilldownClick = useCallback(
    (nextDimension: Attribute) => {
      selectDrilldown(selectedDataPoints, nextDimension);
    },
    [selectDrilldown, selectedDataPoints],
  );

  const onDataPointsSelected = useCallback(
    (points: DataPoint[]) => {
      setSelectedDataPoints(points);
    },
    [setSelectedDataPoints],
  );

  const drilldownMenuItems: MenuItemSection[] = useMemo(
    () => [
      ...(drilldownDimension ? [{ sectionTitle: drilldownDimension?.name }] : []),
      {
        sectionTitle: 'Drill',
        items: availableDrilldowns.map((nextDimension) => ({
          caption: nextDimension.name,
          onClick: () => onMenuDrilldownClick(nextDimension),
        })),
      },
    ],
    [drilldownDimension, availableDrilldowns, onMenuDrilldownClick],
  );

  return (
    <>
      <ContextMenuComponent
        position={contextMenuPos}
        itemSections={drilldownMenuItems}
        closeContextMenu={closeContextMenu}
      />
      {drilldownDimension && !config?.isBreadcrumbsDetached && breadcrumbs}
      {children({
        drilldownFilters,
        drilldownDimension,
        onDataPointsSelected,
        onContextMenu: openContextMenu,
        breadcrumbsComponent: config?.isBreadcrumbsDetached ? breadcrumbs : undefined,
      })}
    </>
  );
};
